GET https://gentle-oasis-71528.herokuapp.com/

###

POST http://localhost:3001/credential
Content-Type: application/json

{
    "name" : "ndadadnnn",
    "username" : "sdsadasl",
    "password" : "88"
}

###

DELETE  http://localhost:3001/deleteAll